### ISSUE TITLE
第四步实现画面的DEBUG方法

### ISSUE THREAD

**Issue by 1144042967** [dustpg/StepFC#1]
作者你好，我是一名JAVA程序员，在尝试使用JAVA重写你的工程。
在第三步实现命令时，通过引用网站的示例日志调试过的。
而到了第四步，第一次实现画面，从reset进入后，五步左右会进入循环，读到的画面数据为全0，CPU写入方法未曾调用过，卡在这个地方几天了，特来求助，希望能找到调试的方法。
我的做法是在循环10000次后，直接调用方法获得 256*240 的颜色数据进行展示的，不知道对不对。

**Comment by dustpg** [comment]
@1144042967

> 作者你好，我是一名JAVA程序员，在尝试使用JAVA重写你的工程。
> 在第三步实现命令时，通过引用网站的示例日志调试过的。
> 而到了第四步，第一次实现画面，从reset进入后，五步左右会进入循环，读到的画面数据为全0，CPU写入方法未曾调用过，卡在这个地方几天了，特来求助，希望能找到调试的方法。
> 我的做法是在循环10000次后，直接调用方法获得 256*240 的颜色数据进行展示的，不知道对不对。

5步就循环可能是博客有些误导, 我说执行10000次, 指的是每帧执行10000次, 并不是执行一次10000次就显示.

```c
/// <summary>
/// 主渲染
/// </summary>
/// <param name="rgba">The RGBA.</param>
extern void main_render(void* rgba) {
    uint32_t* data = rgba;

    for (int i = 0; i != 10000; ++i)
        sfc_cpu_execute_one(g_famicom);

    sfc_do_vblank(g_famicom);

    // 生成调色板颜色
    {
        for (int i = 0; i != 16; ++i) {
            palette_data[i] = sfc_stdpalette[g_famicom->ppu.spindexes[i]];
        }
        palette_data[4 * 1] = palette_data[0];
        palette_data[4 * 2] = palette_data[0];
        palette_data[4 * 3] = palette_data[0];
    }
    // 背景
    const uint8_t* now = g_famicom->ppu.banks[8];
    const uint8_t* bgp = g_famicom->ppu.banks[
        g_famicom->ppu.ctrl & SFC_PPU2000_BgTabl ? 4 : 0];
    for (unsigned i = 0; i != 256 * 240; ++i) {
        data[i] = get_pixel(i & 0xff, i >> 8, now, bgp);
    }
}
```

这条函数每帧都会调用.  如果不是这个原因, 再和博客提到的LOG文件完全一致的话说明官方指令实现完毕了, 博客下一步就是接驳PPU数据, 将PPU的寄存器映射到CPU地址, 读取到全是0的话, 可能是这PPU-CPU数据映射的实现有问题. 可以'写入'的实现打上条件断点, 比如条件是写入地址是$2007. 一路追下去看这么回事.

**Comment by 1144042967** [comment]
非常感谢，在增加外层循环后画面可以正常展示了。后续有问题再来请教。
