### ISSUE TITLE
能不能搞个gcc版本的？

### ISSUE THREAD

**Issue by yunfan** [dustpg/StepFC#2]
如题

**Comment by dustpg** [comment]
@yunfan 在README中就说明了

>同时拥有VS2017和CodeLite的项目工程以保证在不同编译器上能够成功编译.

可以打开CodeLite的'StepFC.workspace', 如果没有CodeLite那就只能手动编译了.

**Comment by dustpg** [comment]
如果没有问题，这个issue就准备关了 @yunfan

**Comment by yunfan** [comment]
额 我来晚了 我没用过IDE 一般都是用make   vs2017/codelite是支持用gcc编译么？

**Comment by dustpg** [comment]
@yunfan 微软的VS支持微软自己MSC以及改造过的Clang, codelite是自己随便找的一个IDE, 这玩意儿支持所有主流编译器, 不过自己是用来简单测试gcc兼容性的, 连怎么调试都还没弄懂
