### ISSUE TITLE
sfc_6502.c 中疑似代码手误的问题

### ISSUE THREAD

**Issue by WqVoon** [dustpg/StepFC#3]
您好，[这里](https://github.com/dustpg/StepFC/blob/master/step2/sfc_6502.c#L395)的 SFC_AM_ABX 是不是应该为 SFC_AM_ZPX 呢？
另：感谢这个 repo 中的代码，受益匪浅:-)

**Comment by dustpg** [comment]
@WqVoon 感谢反馈
